name: Regression

on:
  push:
  # pull_request:
  #   types: [opened, edited]

jobs:
  E2E_Ubuntu:
    runs-on: ${{ matrix.os }}
    matrix:
      os: ['ubuntu-latest', 'windows-latest']

    steps:
      - uses: actions/checkout@v2
      - run: echo test is completed