name: Sample

on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        description: OS
        options: 
        - ubuntu
        - windows
        - macos

jobs:

  E2E_Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: echo regression is done on ${{ github.event.inputs.os }}