name: Sample

on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        description: OS
        options: 
        - ubuntu
        - windows
        - macos
      pull_request:
        type: string

jobs:

  E2E_Ubuntu:
    runs-on: ${{ github.event.inputs.os }}-latest
    steps:
      - run: echo regression is done on ${{ github.event.inputs.os }}
      - if: ${{ github.event.inputs.pull_request }} != ''
        run: echo executed for ${{ github.event.inputs.pull_request }}