name: Sample

on:
  # test
  workflow_dispatch:
  pull_request:
  

jobs:

  E2E_Ubuntu:
    if: ${{ github.event_name != 'issue_comment' || github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          echo ${{ github.event_name }}
      - uses: riskledger/update-pr-description@v2
        with:
          body: "${{ github.event.pull_request.body }} \nupdated"
          token: ${{ secrets.GITHUB_TOKEN }}